# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_auto_20170510_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_offer_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('STUDENT_RESIDENCE', 'Student Residence'), ('ACCOMODATION_WITH_LOCAL_FAMILY', 'Accommodation with local family'), ('HOUSE_APT_SHARE_VISITANTS', 'House or apartment to share with other visitors'), ('HOUSE_OR_PRIV_APT', 'House or private apartment')], max_length=100)),
                ('hosting_host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostinghostprofile', to='accounts.HostingHostProfile', verbose_name='Hosting Host')),
            ],
        ),
    ]
