# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.TextField()),
                ('available_dates', models.DateField(blank=True, help_text='Days in which is possible bookings', null=True, verbose_name='Available dates')),
                ('room_type_offered', models.CharField(choices=[('All property', 'All property'), ('Private Room', 'Private Room'), ('Shared Room', 'Shared Room')], max_length=255, verbose_name='Room Type Offered')),
                ('number_guest_room_type', models.CharField(choices=[('For 1 guest', 'For 1 guest'), ('For 2 guests', 'For 2 guests'), ('3 guests', 'For 3 guests'), ('4 guests', 'For 4 guests'), ('5 guests', 'For 5 guests'), ('6 guests', 'For 6 guests'), ('7 guests', 'For 7 guests'), ('8 guests', 'For 8 guests'), ('9 guests', 'For 9 guests'), ('10 guests', 'For 10 guests')], max_length=255, verbose_name='Number guess in room')),
                ('photographies', models.ImageField(blank=True, null=True, upload_to='hosting-host-photos', verbose_name='Photographies')),
                ('room_value', models.CharField(max_length=128, verbose_name='Price')),
                ('additional_description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offered_services', models.ManyToManyField(help_text='What services do you offer?', related_name='lodgingoffers', to='host_information.LodgingServiceOffer', verbose_name='Offered Services')),
                ('room_information', models.ManyToManyField(help_text='Room caracteristics', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Room caracteristics')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.TextField()),
                ('academic_mobility_programs', models.CharField(choices=[('Academic Semester', 'Academic Semester'), ('Research', 'Research'), ('Rotations or Practices', 'Rotations or practices'), ('Summer School', 'Summer School')], help_text='Available student academic mobility programs', max_length=255, verbose_name='Academic mobility programs')),
                ('additional_description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='study-host-offert-photos', verbose_name='Photography')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledge_topics', taggit.managers.TaggableManager(help_text='A comma-separated list of topics.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Knowledge topics')),
                ('scholarships', models.ManyToManyField(blank=True, help_text='Scholarships availables', to='host_information.Scholarship', verbose_name='Scholarships')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffertList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Oferta de estudios',
                'verbose_name_plural': 'Oferta de estudios',
            },
        ),
        migrations.CreateModel(
            name='StudiesTypeOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Continuing Education studies', 'Continuing Education studies'), ('Technique', 'Technique'), ('Technology', 'Technology'), ('Professional', 'Professional'), ('Specialization', 'Specialization'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de estudio ofertado',
                'verbose_name_plural': 'Tipo de estudios ofertados',
            },
        ),
        migrations.AddField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
            field=models.ManyToManyField(blank=True, to='hosts.StudiesTypeOffered', verbose_name='Tipo de oferta asociada'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_offert_list',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='studies_type_offered', chained_model_field='studies_type_offered_associated', help_text='What are your studies offerts?', to='hosts.StudiesOffertList'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.ManyToManyField(related_name='studiesofferts', to='hosts.StudiesTypeOffered', verbose_name='Studies Type offered'),
        ),
    ]
