# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('lodging_offer_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostel'), ('Student Residence', 'Student Residence'), ('Accommodation with local family', 'Accommodation with local family'), ('House or apartment to share with other visitors', 'House or apartment to share with other visitors'), ('House or private apartment', 'House or private apartment')], max_length=255, verbose_name='Lodging offer type')),
                ('stars', models.CharField(choices=[('1 star', '1 star'), ('2 stars', '2 stars'), ('3 stars', '3 stars'), ('4 stars', '4 stars'), ('5 stars', '5 stars')], max_length=255, verbose_name='Stars numbers')),
                ('available_dates', models.DateField(blank=True, help_text='Days in which is possible bookings', null=True, verbose_name='Available dates')),
                ('room_type_offered', models.CharField(choices=[('All property', 'All property'), ('Private Room', 'Private Room'), ('Shared Room', 'Shared Room')], max_length=255, verbose_name='Room Type Offered')),
                ('number_guest_room_type', models.CharField(choices=[('For 1 guest', 'For 1 guest'), ('For 2 guests', 'For 2 guests'), ('3 guests', 'For 3 guests'), ('4 guests', 'For 4 guests'), ('5 guests', 'For 5 guests'), ('6 guests', 'For 6 guests'), ('7 guests', 'For 7 guests'), ('8 guests', 'For 8 guests'), ('9 guests', 'For 9 guests'), ('10 guests', 'For 10 guests')], max_length=255, verbose_name='Number guess in room')),
                ('bed_type', models.CharField(choices=[('Single bed', 'Single bed'), ('Double bed', 'Double bed')], max_length=10, verbose_name='Bed type')),
                ('bathroom', models.CharField(choices=[('Private bathroom', 'Private bathroom'), ('Shared bathroom', 'Shared bathroom')], max_length=20, verbose_name='Bathroom')),
                ('photographies', models.ImageField(blank=True, null=True, upload_to='hosting-host-photos', verbose_name='Photographies')),
                ('room_value', models.CharField(max_length=128, verbose_name='Price')),
                ('additional_description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('featured_amenities', models.ManyToManyField(help_text='What amenities do you offer?', to='host_information.FeaturesAmenities', verbose_name='Featured Amenities')),
                ('offered_services', models.ManyToManyField(help_text='What services do you offer?', related_name='lodgingoffers', to='host_information.LodgingServiceOffer', verbose_name='Offered Services')),
                ('room_information', models.ManyToManyField(help_text='Room caracteristics', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Room caracteristics')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('institute_character', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Private - Public', 'Private - Public')], max_length=20, verbose_name='Character of the institution')),
                ('students_number', models.CharField(choices=[('Less than a thousand students', 'Less than a thousand students'), ('Between one thousand and ten thousand students', 'Between one thousand and ten thousand students'), ('Between ten thousand and twenty thousand students', 'Between ten thousand and twenty thousand students'), ('More/Greater than twenty thousand students', 'More/Greater than twenty thousand students')], max_length=255, verbose_name='Number of students')),
                ('academic_mobility_programs', models.CharField(choices=[('Academic Semester', 'Academic Semester'), ('Research', 'Research'), ('Rotations or Practices', 'Rotations or practices'), ('Summer School', 'Summer School')], help_text='Available student academic mobility programs', max_length=255, verbose_name='Academic mobility programs')),
                ('duration', models.CharField(choices=[('One month or less', 'One month or less'), ('One to six months', 'One to six months'), ('Six to twelve months', 'Six to twelve months'), ('Twelve to eighteen moths', 'Twelve to eighteen moths'), ('Eighteen to twenty four months', 'Eighteen to twenty four months'), ('Twenty four to Thirty six months', 'Twenty four to Thirty six months'), ('Thirty six to Fourty eight months', 'Thirty six to Fourty eight months'), ('Fourty eight to Sixty months', 'Fourty eight to Sixty months'), ('More/Greater than Sixty months', 'More/Greater than Sixty months')], max_length=255, verbose_name='Duration')),
                ('studies_value', models.CharField(max_length=128, verbose_name='Price')),
                ('additional_description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='study-host-offert-photos', verbose_name='Photography')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('accreditations', models.ManyToManyField(related_name='studiesofferts', to='host_information.Accreditations', verbose_name='High Quality accreditations')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledge_topics', taggit.managers.TaggableManager(help_text='A comma-separated list of topics.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Knowledge topics')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffertList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Oferta de estudios',
                'verbose_name': 'Oferta de estudios',
            },
        ),
        migrations.CreateModel(
            name='StudiesTypeOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de estudios ofertados',
                'verbose_name': 'Tipo de estudio ofertado',
            },
        ),
        migrations.AddField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
            field=models.ManyToManyField(blank=True, to='hosts.StudiesTypeOffered', verbose_name='Tipo de oferta asociada'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.ManyToManyField(related_name='studiesofferts', to='hosts.StudiesTypeOffered', verbose_name='Studies Type offered'),
        ),
    ]
