# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
    ]
