# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='ad_title',
            field=models.CharField(max_length=255),
        ),
    ]
