# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0005_roominformation'),
        ('hosts', '0002_auto_20170517_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='room_information',
            field=models.ManyToManyField(help_text='Room caracteristics', to='host_information.RoomInformation', verbose_name='Room caracteristics'),
        ),
    ]
