# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20170618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostel'), ('Student Residence', 'Student Residence'), ('Accommodation with local family', 'Accommodation with local family'), ('House or apartment to share with other visitors', 'House or apartment to share with other visitors'), ('House or private apartment', 'House or private apartment')], default=1, max_length=255, verbose_name='Lodging offer type'),
            preserve_default=False,
        ),
    ]
