# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_remove_studiesoffert_accreditations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='latitude',
            field=models.CharField(default=1, max_length=255, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='longitude',
            field=models.CharField(default=1, max_length=255, verbose_name='longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='latitude',
            field=models.CharField(default=1, max_length=255, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='longitude',
            field=models.CharField(default=1, max_length=255, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
