# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_lodgingoffer_lodging_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='stars',
            field=models.CharField(choices=[('1 star', '1 star'), ('2 stars', '2 stars'), ('3 stars', '3 stars'), ('4 stars', '4 stars'), ('5 stars', '5 stars')], default=1, max_length=255, verbose_name='Stars numbers'),
            preserve_default=False,
        ),
    ]
