# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_lodgingoffer_room_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='room_value',
            field=models.CharField(default=1, max_length=128, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
