# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20170804_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude'),
        ),
    ]
