# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_lodgingoffer_room_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='additional_description',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='scene',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
