# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0001_initial'),
        ('hosts', '0004_lodgingoffer_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='featured_amenities',
            field=models.ManyToManyField(help_text='What amenities do you offer?', to='host_information.FeaturesAmenities', verbose_name='Featured Amenities'),
        ),
    ]
