# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20170517_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='featured_amenities',
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='available_dates',
            field=models.DateField(blank=True, null=True, verbose_name='Available dates'),
        ),
    ]
