# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_lodgingoffer_featured_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
