# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0007_scholarship'),
        ('taggit', '0002_auto_20150616_2121'),
        ('hosts', '0006_auto_20170608_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudiesOffert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_mobility_programs', models.CharField(choices=[('ACADEMIC_SEMESTER', 'Academic Semester'), ('RESEARCH', 'Research'), ('ROTATIONS_OR_PRACTICES', 'Rotations or practices'), ('SUMMER_SCHOOL', 'Summer School')], help_text='Available student academic mobility programs', max_length=255, verbose_name='Academic mobility programs')),
                ('knowledge_topics', taggit.managers.TaggableManager(help_text='A comma-separated list of topics.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Knowledge topics')),
                ('scholarships', models.ManyToManyField(help_text='Scholarships availables', to='host_information.Scholarship', verbose_name='Scholarships')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffertList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Oferta de estudios',
                'verbose_name': 'Oferta de estudios',
            },
        ),
        migrations.CreateModel(
            name='StudiesTypeOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Continuing Education studies', 'Continuing Education studies'), ('Technique', 'Technique'), ('Technology', 'Technology'), ('Professional', 'Professional'), ('Specialization', 'Specialization'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipo de estudios ofertados',
                'verbose_name': 'Tipo de estudio ofertado',
            },
        ),
        migrations.AddField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
            field=models.ManyToManyField(blank=True, to='hosts.StudiesTypeOffered', verbose_name='Tipo de oferta asociada'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_offert_list',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='studies_type_offered', chained_model_field='studies_type_offered_associated', help_text='What are your studies offerts>?', to='hosts.StudiesOffertList'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.ManyToManyField(to='hosts.StudiesTypeOffered', verbose_name='Studies Type offered'),
        ),
    ]
