# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20170621_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='bathroom',
            field=models.CharField(choices=[('Private bathroom', 'Private bathroom'), ('Shared bathroom', 'Shared bathroom')], default=1, max_length=20, verbose_name='Bathroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='bed_type',
            field=models.CharField(choices=[('Single bed', 'All property'), ('Double bed', 'Private Room')], default=1, max_length=10, verbose_name='Bed type'),
            preserve_default=False,
        ),
    ]
