# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0007_auto_20170611_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='scholarships',
            field=models.ManyToManyField(blank=True, help_text='Scholarships availables', to='host_information.Scholarship', verbose_name='Scholarships'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_offert_list',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='studies_type_offered', chained_model_field='studies_type_offered_associated', help_text='What are your studies offerts?', to='hosts.StudiesOffertList'),
        ),
    ]
