# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20170611_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='study_offert', verbose_name='Photography'),
        ),
    ]
