# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20170621_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
    ]
