# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_studiesoffert_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
        ),
    ]
