# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0002_accreditations'),
        ('hosts', '0009_lodgingoffer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='accreditations',
            field=models.ManyToManyField(related_name='studiesofferts', to='host_information.Accreditations', verbose_name='High Quality accreditations'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='students_number',
            field=models.CharField(choices=[('Less than a thousand students', 'Less than a thousand students'), ('Between one thousand and ten thousand students', 'Between one thousand and ten thousand students'), ('Between ten thousand and twenty thousand students', 'Between ten thousand and twenty thousand students'), ('More/Greater than twenty thousand students', 'More/Greater than twenty thousand students')], default=1, max_length=255, verbose_name='Number of students'),
            preserve_default=False,
        ),
    ]
