# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_auto_20170621_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='duration',
            field=models.CharField(choices=[('One month or less', 'One month or less'), ('One to six months', 'One to six months'), ('Six to twelve months', 'Six to twelve months'), ('Twelve to eighteen moths', 'Twelve to eighteen moths'), ('Eighteen to twenty four months', 'Eighteen to twenty four months'), ('Twenty four to Thirty six months', 'Twenty four to Thirty six months'), ('Thirty six to Fourty eight months', 'Thirty six to Fourty eight months'), ('Fourty eight to Sixty months', 'Fourty eight to Sixty months'), ('More/Greater than Sixty months', 'More/Greater than Sixty months')], default=1, max_length=255, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='institute_character',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Private - Public', 'Private - Public')], default=1, max_length=20, verbose_name='Character of the institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='studies_value',
            field=models.CharField(default=1, max_length=128, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
