# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_auto_20170613_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='scene',
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='birth_year',
            field=models.DateField(blank=True, help_text='Days in which is possible bookings', null=True, verbose_name='Available dates'),
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='number_guest_room_type',
            field=models.CharField(choices=[('ONE_GUEST', 'For 1 guest'), ('ONE_GUEST', 'For 2 guests'), ('ONE_GUEST', 'For 3 guests'), ('ONE_GUEST', 'For 4 guests'), ('ONE_GUEST', 'For 5 guests'), ('ONE_GUEST', 'For 6 guests'), ('ONE_GUEST', 'For 7 guests'), ('ONE_GUEST', 'For 8 guests'), ('ONE_GUEST', 'For 9 guests'), ('ONE_GUEST', 'For 10 guests')], default=1, max_length=255, verbose_name='Room Type Offered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='photographies',
            field=models.ImageField(blank=True, null=True, upload_to='lodgingphoto', verbose_name='Photographies'),
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='room_type_offered',
            field=models.CharField(choices=[('ALL_PROPERTY', 'All property'), ('PRIVATE_ROOM', 'Private Room'), ('SHARED_ROOM', 'Shared Room')], default=1, max_length=255, verbose_name='Room Type Offered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='additional_description',
            field=models.TextField(),
        ),
    ]
