# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_auto_20170621_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiestypeoffered',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studiestypeoffered',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
