# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_auto_20170621_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
