# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0014_auto_20170613_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiesoffert',
            old_name='institution',
            new_name='created_by',
        ),
    ]
