# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0014_auto_20170623_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiesoffert',
            old_name='updated_at',
            new_name='pub_date',
        ),
    ]
