# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20170623_1714'),
        ('hosts', '0002_auto_20170617_2047'),
    ]

    operations = [
    ]
