# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20170614_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='photographies',
            field=models.ImageField(blank=True, null=True, upload_to='hosting-host-photos', verbose_name='Photographies'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='study-host-offert-photos', verbose_name='Photography'),
        ),
    ]
