# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0016_auto_20170614_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
