# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0016_merge_20170625_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesoffert',
            name='ad_title',
            field=models.CharField(max_length=255),
        ),
    ]
