# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_studiesoffert_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='number_guest_room_type',
            field=models.CharField(choices=[('For 1 guest', 'For 1 guest'), ('For 2 guests', 'For 2 guests'), ('3 guests', 'For 3 guests'), ('4 guests', 'For 4 guests'), ('5 guests', 'For 5 guests'), ('6 guests', 'For 6 guests'), ('7 guests', 'For 7 guests'), ('8 guests', 'For 8 guests'), ('9 guests', 'For 9 guests'), ('10 guests', 'For 10 guests')], max_length=255, verbose_name='Number guess in room'),
        ),
    ]
