# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0019_auto_20170614_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffert',
            name='slug',
        ),
    ]
