# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0020_remove_studiesoffert_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='additional_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
