# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_studiesoffert_additional_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesoffert',
            name='academic_mobility_programs',
            field=models.CharField(choices=[('Academic Semester', 'Academic Semester'), ('Research', 'Research'), ('Rotations or Practices', 'Rotations or practices'), ('Summer School', 'Summer School')], help_text='Available student academic mobility programs', max_length=255, verbose_name='Academic mobility programs'),
        ),
    ]
