# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0022_auto_20170615_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='slug',
        ),
    ]
