# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0023_remove_lodgingoffer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='offered_services',
            field=models.ManyToManyField(help_text='What services do you offer?', related_name='lodgingoffers', to='host_information.LodgingServiceOffer', verbose_name='Offered Services'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_information',
            field=models.ManyToManyField(help_text='Room caracteristics', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Room caracteristics'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.ManyToManyField(related_name='studiesofferts', to='hosts.StudiesTypeOffered', verbose_name='Studies Type offered'),
        ),
    ]
