# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinghostprofile',
            name='featured_amenities',
            field=models.ManyToManyField(help_text='What amenities do you offer?', to='host_information.FeaturesAmenities', verbose_name='Featured Amenities'),
        ),
        migrations.AddField(
            model_name='hostinghostprofile',
            name='lodging_offer_type',
            field=models.ManyToManyField(help_text='What lodging offer type?', to='host_information.LodgingOfferType', verbose_name='Lodging Offer Type'),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='research_groups',
            field=models.ManyToManyField(help_text='What are your research groups?', to='host_information.ResearchGroups', verbose_name='Research Groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(to='host_information.EntertainmentActivities'),
        ),
        migrations.AddField(
            model_name='user',
            name='speak_languages',
            field=models.ManyToManyField(help_text='What services do you offer?', related_name='users', to='host_information.SpeakLanguages', verbose_name='Languages'),
        ),
    ]
