# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170726_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveprofile',
            name='companies_to_visit',
        ),
    ]
