# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entertainmenthostprofile_executiveprofile_hostinghostprofile_innovationhostprofile_otherserviceshost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, help_text='Usuario con perfil de ejecutivo', verbose_name='Ejecutivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, help_text='Usuario con perfil de profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Usuario con perfil de estudiante', verbose_name='Estudiante'),
        ),
    ]
