# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170616_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='students_number',
            field=models.CharField(choices=[('Less than a thousand students', 'Less than a thousand students'), ('Between one thousand and ten thousand students', 'Between one thousand and ten thousand students'), ('Between ten thousand and twenty thousand students', 'Between ten thousand and twenty thousand students'), ('More/Greater than twenty thousand students', 'More/Greater than twenty thousand students')], max_length=255, verbose_name='Number of students'),
        ),
    ]
