# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_executiveprofile_companies_to_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveprofile',
            name='occupation',
        ),
    ]
