# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170323_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speak_languages',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
