# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_executiveprofile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyhostprofile',
            name='research_groups',
        ),
    ]
