# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170718_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('P', 'Person'), ('I', 'Institution')], default=False, max_length=10, verbose_name='User type'),
        ),
    ]
