# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170323_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_education_school',
            field=models.CharField(default=1, max_length=128, verbose_name='current education institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extra_occupation',
            field=models.CharField(default=1, max_length=128, verbose_name='extra occupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='origin_education_school',
            field=models.CharField(default=1, max_length=128, verbose_name='origin education institute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, help_text='Executive profile', verbose_name='Executive'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, help_text='Professor profile', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Student profile', verbose_name='Student'),
        ),
    ]
