# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name'),
        ),
    ]
