# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_enterprise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='enterprise name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(blank=True, to='host_information.EntertainmentActivities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='speak_languages',
            field=models.ManyToManyField(blank=True, help_text='What languages do you speak?', related_name='users', to='host_information.SpeakLanguages', verbose_name='Languages'),
        ),
    ]
