# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170325_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=False, max_length=4, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='speak_languages',
            field=models.CharField(max_length=255),
        ),
    ]
