# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170331_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=False, max_length=10, verbose_name='genero'),
        ),
    ]
