# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170331_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='occupation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
