# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170402_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
