# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_executiveprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city_of_origin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country_current_residence',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_entertainment_host',
            field=models.BooleanField(default=False, help_text='Entertainment host profile', verbose_name='Entertainment host'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hosting_host',
            field=models.BooleanField(default=False, help_text='Hosting host profile', verbose_name='Hosting host'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_innovation_host',
            field=models.BooleanField(default=False, help_text='Innovation host profile', verbose_name='Innovation host'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_other_services_host',
            field=models.BooleanField(default=False, help_text='Other services host profile', verbose_name='Other services host'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_study_host',
            field=models.BooleanField(default=False, help_text='Study host profile', verbose_name='Study host'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please use the following format: <em>+<counry-code><phone-number></em>.', max_length=128),
        ),
    ]
