# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170411_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveprofile',
            name='occupation',
        ),
    ]
