# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 00:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170419_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='complete_studies_school',
            field=models.CharField(default=1, max_length=255, verbose_name='Institution where completed his previous studies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='educational_titles',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entertainment_activities_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Entertainment activities of your choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='knowledge_topics_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Areas of knowledge of your choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Letters, digits and @/./+/-/_ only.', max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid email address.', 'invalid')]),
        ),
    ]
