# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170426_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speak_languages',
            field=models.CharField(blank=True, choices=[('SPA', 'Spanish'), ('ENG', 'English'), ('DEU', 'German'), ('FRA', 'French'), ('POR', 'Portuguese')], max_length=255),
        ),
    ]
