# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170509_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='complete_studies_school',
            field=models.CharField(default=1, max_length=255, verbose_name='Institution where completed his previous studies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='current_education_school',
            field=models.CharField(default=1, max_length=128, verbose_name='Institution of education to which is linked in the current residence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='educational_titles',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='entertainment_activities_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Entertainment activities of your choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='knowledge_topics_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Areas of knowledge of your choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='origin_education_school',
            field=models.CharField(default=1, max_length=128, verbose_name='Origin education institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='research_groups',
            field=models.CharField(default=1, max_length=255, verbose_name='Research groups to which it belongs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_education_school',
            field=models.CharField(max_length=128, verbose_name='Institution of education to which is linked in the current residence'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extra_occupation',
            field=models.CharField(max_length=128, verbose_name='Extra occupation'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='origin_education_school',
            field=models.CharField(max_length=128, verbose_name='Origin education institute'),
        ),
    ]
