# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170509_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='autorship_publications',
            field=models.CharField(default=1, max_length=255, verbose_name='Publications of its authorship'),
            preserve_default=False,
        ),
    ]
