# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20170509_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveprofile',
            name='culturals_arthistic',
        ),
        migrations.RemoveField(
            model_name='executiveprofile',
            name='ecological',
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='companies_to_visit',
            field=models.CharField(default=1, max_length=255, verbose_name='Companies to Visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='complete_studies_school',
            field=models.CharField(default=1, max_length=255, verbose_name='Institution where completed his previous studies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='educational_titles',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='innovation_topics_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Areas of innovation of your choice'),
            preserve_default=False,
        ),
    ]
