# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170509_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhostprofile',
            name='high_quality_accreditations',
            field=models.CharField(default=1, max_length=255, verbose_name='Accreditations of high quality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='institute_character',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('MIXED', 'Private - Public')], default=False, max_length=7, verbose_name='Character of the institution'),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='institution_type',
            field=models.CharField(default=1, max_length=255, verbose_name='Institution type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='knowledge_topics_choice',
            field=models.CharField(default=1, max_length=255, verbose_name='Areas of knowledge of your choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='rankings_classification',
            field=models.CharField(default=1, max_length=255, verbose_name='Classification in ranking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='strengths',
            field=models.CharField(default=1, max_length=255, verbose_name='Strengths'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='students_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of students'),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='studies_offert_list',
            field=models.CharField(choices=[('Continuing education studies', (('SPANISH_FOREIGNS', 'Spanish for foreigns'), ('ENGLISH', 'English'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=1, max_length=255, verbose_name='Studies Offert List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='studies_type_offered',
            field=models.CharField(default=1, max_length=255, verbose_name='Type of studies offered'),
            preserve_default=False,
        ),
    ]
