# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170426_0351'),
        ('accounts', '0021_auto_20170509_0125'),
        ('accounts', '0025_auto_20170509_2107'),
    ]

    operations = [
    ]
