# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_20170510_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='studies_offert_list',
            field=models.CharField(choices=[('Continuing education studies', (('SPANISH_FOREIGNS', 'Spanish for foreigns'), ('ENGLISH', 'English'))), ('Professional', (('SYSTEMS_ENGINEERING', 'Systems Engineering'), ('BIOMEDICAL_ENGINEERING', 'Biomedical Engineering'))), ('unknown', 'Unknown')], max_length=255, verbose_name='Studies Offert List'),
        ),
    ]
