# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0003_auto_20170510_2031'),
        ('accounts', '0027_auto_20170510_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entertainment_activities_choice',
        ),
        migrations.AddField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(to='host_information.EntertainmentActivities'),
        ),
    ]
