# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170510_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudiesOffertList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Oferta de estudios',
                'verbose_name': 'Oferta de estudios',
            },
        ),
        migrations.CreateModel(
            name='StudiesTypeOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipo de estudios ofertados',
                'verbose_name': 'Tipo de estudio ofertado',
            },
        ),
        migrations.RemoveField(
            model_name='studyhostprofile',
            name='studies_offert_list',
        ),
        migrations.RemoveField(
            model_name='studyhostprofile',
            name='studies_type_offered',
        ),
        migrations.AddField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
            field=models.ManyToManyField(blank=True, to='accounts.StudiesTypeOffered', verbose_name='Tipo de oferta asociada'),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='studies_offert_list',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='studies_type_offered', chained_model_field='studies_type_offered_associated', to='accounts.StudiesOffertList', verbose_name='Studies Offert List'),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='studies_type_offered',
            field=models.ManyToManyField(to='accounts.StudiesTypeOffered', verbose_name='Studies Type offered'),
        ),
    ]
