# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20170606_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='institution_type',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('TECH_SCHOOL', 'Technological School'), ('UNIV_INST', 'University Institution'), ('PROF_TECH_INST', 'Professional Technological Institution'), ('CONTINUAL_EDUCATION_CENTER', 'Continual Education Center')], max_length=255, verbose_name='Institution Type'),
        ),
    ]
