# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20170606_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='students_number',
            field=models.CharField(choices=[('ZERO_T0_HUNDRED', '0 a 100 personas'), ('HUNDRED_TO_THREE_HUNDRED', '100 a 300 personas'), ('THREE_HUNDRED_TO_ONE_THOUSAND', '300 a 1000 personas'), ('ONE_THOUSAND_TO_TWENTY_ONE_THOUSAND_FIVE_HUNDRED', '1000 a 21.500 personas '), ('GREATER_THAN_TWENTY_ONE_THOUSAND_FIVE_HUNDRED', 'Mayor a 21.500 personas')], default=1, max_length=255, verbose_name='Number of students'),
            preserve_default=False,
        ),
    ]
