# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20170606_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='institute_character',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('MIXED', 'Private - Public')], max_length=7, verbose_name='Character of the institution'),
        ),
    ]
