# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170606_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiestypeoffered',
            name='name',
            field=models.CharField(choices=[('Continuing Education studies', 'Continuing Education studies'), ('Technique', 'Technique'), ('Technology', 'Technology'), ('Professional', 'Professional'), ('Specialization', 'Specialization'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, verbose_name='nombre'),
        ),
    ]
