# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20170606_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
            field=models.ManyToManyField(blank=True, to='accounts.StudiesTypeOffered', verbose_name='Tipo de oferta asociada'),
        ),
    ]
