# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0006_researchgroups'),
        ('accounts', '0035_auto_20170606_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhostprofile',
            name='photography',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studyhostprofile',
            name='research_groups',
            field=models.ManyToManyField(help_text='What are your research groups ?', to='host_information.ResearchGroups', verbose_name='Research Groups'),
        ),
    ]
