# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0006_researchgroups'),
        ('accounts', '0036_auto_20170607_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinghostprofile',
            name='featured_amenities',
            field=models.ManyToManyField(help_text='What amenities do you offer?', to='host_information.FeaturesAmenities', verbose_name='Featured Amenities'),
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='research_groups',
            field=models.ManyToManyField(help_text='What are your research groups?', to='host_information.ResearchGroups', verbose_name='Research Groups'),
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='studies_offert_list',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='studies_type_offered', chained_model_field='studies_type_offered_associated', help_text='What are your studies offerts>?', to='accounts.StudiesOffertList'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=10, verbose_name='Gender'),
        ),
    ]
