# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_hostinghostprofile_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhostprofile',
            name='academic_mobility_programs',
            field=models.CharField(choices=[('ACADEMIC_SEMESTER', 'Academic Semester'), ('RESEARCH', 'Research'), ('ROTATIONS_OR_PRACTICES', 'Rotations or practices'), ('SUMMER_SCHOOL', 'Summer School')], default=1, help_text='Available student academic mobility programs', max_length=255, verbose_name='Academic mobility programs'),
            preserve_default=False,
        ),
    ]
