# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0007_scholarship'),
        ('accounts', '0039_studyhostprofile_academic_mobility_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhostprofile',
            name='scholarships',
            field=models.ManyToManyField(help_text='Scholarships availables', to='host_information.Scholarship', verbose_name='Scholarships'),
        ),
    ]
