# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_studyhostprofile_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Photo'),
        ),
    ]
