# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20170611_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffertlist',
            name='studies_type_offered_associated',
        ),
        migrations.DeleteModel(
            name='StudiesOffertList',
        ),
        migrations.DeleteModel(
            name='StudiesTypeOffered',
        ),
    ]
