# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20170613_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinghostprofile',
            name='photography',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Photo'),
        ),
    ]
