# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0008_lodgingoffertype'),
        ('accounts', '0047_auto_20170613_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinghostprofile',
            name='lodging_offer_type',
        ),
        migrations.AddField(
            model_name='hostinghostprofile',
            name='lodging_offer_type',
            field=models.ManyToManyField(help_text='What lodging offer type?', to='host_information.LodgingOfferType', verbose_name='Lodging Offer Type'),
        ),
    ]
