# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20170613_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinghostprofile',
            name='stars',
            field=models.PositiveIntegerField(blank=True, help_text='Number of stars', null=True, verbose_name='Stars'),
        ),
    ]
