# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 20, 43, 6, 725850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 20, 43, 6, 725342, tzinfo=utc)),
        ),
    ]
