# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'MODELNAMEs',
                'verbose_name': 'Entertainment Activities',
            },
        ),
    ]
