# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0002_entertainmentactivities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertainmentactivities',
            options={'verbose_name': 'Entertainment Activities', 'verbose_name_plural': 'Entertainment Activities'},
        ),
        migrations.AlterModelOptions(
            name='speaklanguages',
            options={'verbose_name': 'Speak Language', 'verbose_name_plural': 'Speak Languages'},
        ),
        migrations.AlterField(
            model_name='entertainmentactivities',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
