# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0003_auto_20170510_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'What amenities do you offer?',
                'verbose_name_plural': 'What amenities do you offer?',
            },
        ),
        migrations.CreateModel(
            name='LodgingServiceOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Offered Services',
                'verbose_name_plural': 'Offered Services',
            },
        ),
    ]
