# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0004_featuresamenities_lodgingserviceoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Room caracteristics',
                'verbose_name': 'Room caracteristics',
            },
        ),
    ]
