# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0006_researchgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('who_can_apply', models.TextField()),
                ('application_process', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
            },
        ),
    ]
