# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0007_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOfferType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_offer_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('STUDENT_RESIDENCE', 'Student Residence'), ('ACCOMODATION_WITH_LOCAL_FAMILY', 'Accommodation with local family'), ('HOUSE_APT_SHARE_VISITANTS', 'House or apartment to share with other visitors'), ('HOUSE_OR_PRIV_APT', 'House or private apartment')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Research Groups',
                'verbose_name': 'Research Groups',
            },
        ),
    ]
