# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0008_lodgingoffertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgingoffertype',
            options={'verbose_name': 'Lodging Offer Type', 'verbose_name_plural': 'Lodging Offer Type'},
        ),
        migrations.RemoveField(
            model_name='lodgingoffertype',
            name='lodging_offer_type',
        ),
        migrations.AddField(
            model_name='lodgingoffertype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
