# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0010_auto_20170616_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroups',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
